# === Seed config (generated by postprocessing_full.ipynb) ===
SEED       = 3
TRAIN_PATH = '/pscratch/sd/p/pvashi/SciDAC/NiNaCl/models/fixed/gen1/seed_3/train.extxyz'
# =============================================================

#!/usr/bin/env python
# coding: utf-8
# Training script body — SEED and TRAIN_PATH are prepended by
# the setup_seeds cell in postprocessing_full.ipynb when copying to seed_N/

import sys
sys.path.insert(0, '/pscratch/sd/p/pvashi/Models/cace')

import numpy as np
import torch
import logging
import json

import cace
from cace.representations import Cace
from cace.modules import PolynomialCutoff, BesselRBF
from cace.models.atomistic import NeuralNetworkPotential
from cace.tasks.train import TrainingTask

torch.set_default_dtype(torch.float32)
cace.tools.setup_logger(level='INFO')

cutoff = 5.5

with open('/pscratch/sd/p/pvashi/SciDAC/NiNaCl/data/reference_energies.json', 'r') as f:
    ref_energies = json.load(f)

atomic_energies = {28: ref_energies['Ni'], 11: ref_energies['Na'], 17: ref_energies['Cl']}

logging.info("reading data")
collection = cace.tasks.get_dataset_from_xyz(
    train_path=TRAIN_PATH,
    valid_fraction=0.1,
    seed=SEED,
    cutoff=cutoff,
    data_key={'energy': 'energy', 'forces': 'forces'},
    atomic_energies=atomic_energies,
)

batch_size = 4
train_loader = cace.tasks.load_data_loader(collection=collection, data_type='train', batch_size=batch_size)
valid_loader = cace.tasks.load_data_loader(collection=collection, data_type='valid', batch_size=4)

use_device = 'cuda'
device = cace.tools.init_device(use_device)
logging.info(f"device: {use_device}")

logging.info("building CACE representation")
radial_basis = BesselRBF(cutoff=cutoff, n_rbf=6, trainable=True)
cutoff_fn    = PolynomialCutoff(cutoff=cutoff)

cace_representation = Cace(
    zs=[28, 11, 17],
    n_atom_basis=5,
    embed_receiver_nodes=True,
    cutoff=cutoff,
    cutoff_fn=cutoff_fn,
    radial_basis=radial_basis,
    n_radial_basis=12,
    max_l=3,
    max_nu=3,
    num_message_passing=0,
    type_message_passing=['Bchi'],
    args_message_passing={'Bchi': {'shared_channels': False, 'shared_l': False}},
    forward_features=['atomic_numbers'],
    device=device,
    timeit=False,
)
cace_representation.to(device)
logging.info(f"Representation: {cace_representation}")

sr_energy = cace.modules.atomwise.Atomwise(
    n_layers=3, output_key='SR_energy', n_hidden=[48, 32],
    use_batchnorm=False, add_linear_nn=True)

q = cace.modules.Atomwise(
    n_layers=3, n_hidden=[48, 32], n_out=1,
    per_atom_output_key='q', output_key='tot_q',
    residual=False, add_linear_nn=True, bias=False)

mw = cace.modules.MetalWall(metal_atomic_numbers=28, output_key='q_mw')

ep = cace.modules.EwaldPotential(
    dl=2, sigma=1.0, feature_key='q_mw', output_key='ewald_potential',
    remove_self_interaction=False, aggregation_mode='sum')

e_add  = cace.modules.FeatureAdd(feature_keys=['SR_energy', 'ewald_potential'], output_key='CACE_energy')
forces = cace.modules.Forces(energy_key='CACE_energy', forces_key='CACE_forces')

cace_nnp = NeuralNetworkPotential(
    input_modules=None,
    representation=cace_representation,
    output_modules=[sr_energy, q, mw, ep, e_add, forces],
)
cace_nnp.to(device)

from cace.tools import Metrics
e_metric = Metrics(target_name='energy', predict_name='CACE_energy', name='e/atom', per_atom=True)
f_metric = Metrics(target_name='forces',  predict_name='CACE_forces', name='f')

optimizer_args = {'lr': 5e-3, 'betas': (0.99, 0.999)}
scheduler_args = {'step_size': 20, 'gamma': 0.5}

force_loss = cace.tasks.GetLoss(target_name='forces', predict_name='CACE_forces',
                                 loss_fn=torch.nn.MSELoss(), loss_weight=1000)

# --- Loop 1: low energy weight ---
logging.info("First train loop:")
energy_loss = cace.tasks.GetLoss(target_name='energy', predict_name='CACE_energy',
                                  loss_fn=torch.nn.MSELoss(), loss_weight=0.1)
for _ in range(5):
    task = TrainingTask(
        model=cace_nnp, losses=[energy_loss, force_loss], metrics=[e_metric, f_metric],
        device=device, optimizer_args=optimizer_args,
        scheduler_cls=torch.optim.lr_scheduler.StepLR, scheduler_args=scheduler_args,
        max_grad_norm=10, ema=False, ema_start=10, warmup_steps=5,
    )
    task.fit(train_loader, valid_loader, epochs=40, screen_nan=False)
task.save_model('model.pth')
cace_nnp.to(device)

# --- Loop 2 ---
logging.info("Second train loop:")
energy_loss = cace.tasks.GetLoss(target_name='energy', predict_name='CACE_energy',
                                  loss_fn=torch.nn.MSELoss(), loss_weight=1)
task.update_loss([energy_loss, force_loss])
task.fit(train_loader, valid_loader, epochs=100, screen_nan=False)
task.save_model('model-2.pth')
cace_nnp.to(device)

# --- Loop 3 ---
logging.info("Third train loop:")
energy_loss = cace.tasks.GetLoss(target_name='energy', predict_name='CACE_energy',
                                  loss_fn=torch.nn.MSELoss(), loss_weight=10)
task.update_loss([energy_loss, force_loss])
task.fit(train_loader, valid_loader, epochs=100, screen_nan=False)
task.save_model('model-3.pth')

# --- Loop 4 ---
logging.info("Fourth train loop:")
energy_loss = cace.tasks.GetLoss(target_name='energy', predict_name='CACE_energy',
                                  loss_fn=torch.nn.MSELoss(), loss_weight=1000)
task.update_loss([energy_loss, force_loss])
task.fit(train_loader, valid_loader, epochs=100, screen_nan=False)
task.save_model('model-4.pth')

logging.info("Finished")
trainable_params = sum(p.numel() for p in cace_nnp.parameters() if p.requires_grad)
logging.info(f"Number of trainable parameters: {trainable_params}")
